version: '3'
services:
  kafka-raw:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-raw:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-raw:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-metrics:
    image: bitnami/kafka:latest
    ports:
      - "9094:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-metrics:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-metrics:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-predictions:
    image: bitnami/kafka:latest
    ports:
      - "9096:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-predictions:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-predictions:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - kafka-raw
      - kafka-metrics
      - kafka-predictions
